#!/usr/bin/env python3
"""Trigger training entrypoint — the contract seam between the Node CLI and the
livekit-wakeword engine.

Node hands us a JSON job spec and reads JSONL progress + a final metrics line off
stdout; nothing else in the system knows livekit-wakeword internals. Library logs
go to stderr, so stdout carries only our JSONL (the Node side parses line-by-line
and ignores anything that isn't JSON, so stray output is harmless either way).

Job spec (argv[1] = path to a JSON file, or '-' for stdin):

    {
      "name": "demo",
      "phrase": "Hey ThinkSuit",
      "positiveDir": "/abs/path/to/samples/positive",   # optional
      "negativeDir": "/abs/path/to/samples/negative",   # optional
      "outPath": "/abs/path/to/exported.onnx",          # where to copy the result
      "mode": "initial" | "augment",                    # advisory; see below
      "params": { "n_samples": 10000, "steps": 50000, ... }   # initial only
    }

Run with cwd = this training/ dir (so ./data and ./output resolve to the shared
synthetic cache). `generate` runs only when the synthetic base is absent — so an
augment re-uses the existing synthetic clips (mix -> augment -> train -> export),
which is why it is far cheaper than a first run.
"""
from __future__ import annotations

import json
import logging
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CONFIGS = HERE / "configs"
TOOLS = HERE.parent / "tools"

# Library + our own logs go to stderr; stdout is reserved for JSONL.
logging.basicConfig(level=logging.INFO, format="%(message)s", stream=sys.stderr)

sys.path.insert(0, str(TOOLS))  # make mix.py's oversampling logic importable


def emit(event: str, **fields) -> None:
    print(json.dumps({"event": event, **fields}), flush=True)


def read_job() -> dict:
    arg = sys.argv[1] if len(sys.argv) > 1 else "-"
    text = sys.stdin.read() if arg == "-" else Path(arg).read_text()
    return json.loads(text)


CONFIG_TEMPLATE = """# Generated by train.py for trigger '{name}'. Do not hand-edit — the counts must
# stay stable across initial + augment runs so real-voice mixing offsets line up.
model_name: {name}
target_phrases:
  - "{phrase}"

custom_negative_phrases: []

tts_backend: piper_vits

n_samples: {n_samples}
n_samples_val: {n_samples_val}
n_background_samples: {n_background_samples}
n_background_samples_val: {n_background_samples_val}

steps: {steps}

model:
  model_type: conv_attention
  model_size: small

batch_n_per_class:
  positive: 50
  adversarial_negative: 50
  ACAV100M_sample: 0
  background_noise: 50

data_dir: ./data
output_dir: ./output
"""

DEFAULT_PARAMS = {
    "n_samples": 10000,
    "n_samples_val": 2000,
    "n_background_samples": 200,
    "n_background_samples_val": 40,
    "steps": 50000,
}


def ensure_config(job: dict) -> Path:
    """Write the per-trigger config on first run; reuse it thereafter so the
    synthetic counts (and thus mix offsets) never drift."""
    name = job["name"]
    path = CONFIGS / f"{name}.yaml"
    if path.exists():
        return path
    params = {**DEFAULT_PARAMS, **(job.get("params") or {})}
    CONFIGS.mkdir(parents=True, exist_ok=True)
    path.write_text(CONFIG_TEMPLATE.format(name=name, phrase=job["phrase"], **params))
    return path


def mix_real_voice(cfg, job: dict) -> None:
    """Oversample the user's recordings into the synthetic positive/negative sets
    using mix.py's logic (idempotent — clears prior injections first)."""
    import mix  # from tools/, on sys.path

    md = cfg.model_output_dir
    pos = job.get("positiveDir")
    neg = job.get("negativeDir")

    def has_clips(d):
        return d and Path(d).exists() and any(Path(d).glob("clip_*.wav"))

    if has_clips(pos):
        emit("phase", phase="mix-positive", status="start")
        mix.mix_group(
            "positives", pos,
            md / "positive_train", md / "positive_test",
            cfg.n_samples, cfg.n_samples_val,
            5000, 300, 15, 0.05, 0.5,
        )
        emit("phase", phase="mix-positive", status="done")
    if has_clips(neg):
        emit("phase", phase="mix-negative", status="start")
        mix.mix_group(
            "negatives", neg,
            md / "negative_train", md / "negative_test",
            mix.NEG_OFFSET, mix.NEG_OFFSET,
            5000, 300, 15, 0.05, 0.5,
        )
        emit("phase", phase="mix-negative", status="done")


def main() -> None:
    job = read_job()
    name = job["name"]
    out_path = Path(job["outPath"])
    emit("start", name=name, phrase=job.get("phrase"))

    from livekit.wakeword.config import load_config
    from livekit.wakeword.data.augment import run_augment
    from livekit.wakeword.data.features import run_extraction
    from livekit.wakeword.data.generate import run_generate
    from livekit.wakeword.eval.evaluate import run_eval
    from livekit.wakeword.export.onnx import run_export
    from livekit.wakeword.training.trainer import run_train

    config_path = ensure_config(job)
    cfg = load_config(str(config_path))
    emit("phase", phase="config", status="done", config=str(config_path))

    synthetic_base = cfg.model_output_dir / "positive_train"
    do_generate = job.get("mode") == "initial" or not synthetic_base.exists()

    if do_generate:
        emit("phase", phase="generate", status="start")
        run_generate(cfg)
        emit("phase", phase="generate", status="done")
    else:
        emit("phase", phase="generate", status="skipped", reason="synthetic base present")

    mix_real_voice(cfg, job)

    emit("phase", phase="augment", status="start")
    run_augment(cfg)
    run_extraction(cfg)
    emit("phase", phase="augment", status="done")

    emit("phase", phase="train", status="start", steps=cfg.steps)
    run_train(cfg)
    emit("phase", phase="train", status="done")

    emit("phase", phase="export", status="start")
    onnx_path = run_export(cfg)
    emit("phase", phase="export", status="done")

    emit("phase", phase="eval", status="start")
    results = run_eval(cfg, onnx_path)
    emit("phase", phase="eval", status="done")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(onnx_path, out_path)

    metrics = {
        "aut": results.get("aut"),
        "fpph": results.get("fpph"),
        "recall": results.get("recall"),
        "threshold": results.get("threshold"),
    }
    emit("done", onnxPath=str(out_path), metrics=metrics)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:  # noqa: BLE001 — surface any failure as a JSONL error
        emit("error", message=str(e))
        sys.exit(1)
